### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by paulienuh** [paulienuh/inspiring-figures#1]
- [x] Create React App
- [x] Try out Flexbox
- [x] Put profile images up
- [ ] Create a pop-up window for each profile with short bio, social media accounts and links to blog and video
- [ ] Animated center/logo?
- [ ] Make fully responsive for mobile devices

**Comment by paulienuh** [comment]
For pop-up window, maybe? https://github.com/yjose/reactjs-popup
