### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by paulienuh** [paulienuh/inspiring-figures#1]
- [ ] CSS Grid/Flexbox?
- [ ] Add profiles
- [ ] Add pop-up with short bio
- [ ] Add CTA buttons: YouTube, Blog post
- [ ] Add social media buttons
- [ ] Animated center/logo(?)
- [ ] Responsiveness
